name: 'Department of Veterans Affairs New User Automation'
author: 'Brett Logan'
description: 'Automates the addition of new users into the VA org'
inputs:
  body:
    description: The body of the newly created issue
    required: true
    default: ${{ toJSON(github.event.issue.body) }}
  issue_number:
    description: The GitHub issue number
    required: true
    default: ${{ github.event.issue.number }}
  org:
    description: The GitHub org containing the repo
    required: true
    default: ${{ github.repository_owner }}
  repo:
    description: The repo where the GitHub issue exists
    required: true
  success_message:
    description: Comment body on success invitation
    required: true
    default: User successfuly invited
  suffix:
    description: The email domain of the organization
    required: true
  team:
    description: The default team to add all users to
    required: true
  token:
    description: GitHub Admin PAT to open issues and comment
    required: true
  user:
    description: G-Mail user who owns the secrets
    required: true
  secret:
    description: G-Mail app password
    required: true
  from:
    description: E-mail for the From header
    required: true
  template:
    description: String template to form the email body from
    required: true
runs:
  using: node12
  main: dist/index.js
